// This file is auto-generated. Do not edit this file.
// Generated from scripts/setup-env.js

export const LOCAL_IP_ADDRESS = '192.168.0.210';
export const DFX_NETWORK = 'local';
export const CANISTER_ID_INTERNET_IDENTITY = 'rdmx6-jaaaa-aaaaa-aaadq-cai';
export const CANISTER_ID_BACKEND = 'uxrrr-q7777-77774-qaaaq-cai';
export const CANISTER_ID_FRONTEND = 'u6s2n-gx777-77774-qaaba-cai';
export const CANISTER_ID_II_INTEGRATION = 'uzt4z-lp777-77774-qaabq-cai';
export const CANISTER_ID_ISSUER = 'umunu-kh777-77774-qaaca-cai';
export const EXPO_SCHEME = 'expo-icp-supply-chain';
